"""empty message

Revision ID: 2277ce263239
Revises: 
Create Date: 2025-05-04 15:49:02.103762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2277ce263239'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toys', sa.JSON(), nullable=False),
    sa.Column('hats', sa.JSON(), nullable=False),
    sa.Column('collars', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('graveyard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=64), nullable=False),
    sa.Column('pet_type', sa.String(length=64), nullable=False),
    sa.Column('death_time', sa.DateTime(), nullable=False),
    sa.Column('cause_of_death', sa.String(length=100), nullable=True),
    sa.Column('original_pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toys', sa.JSON(), nullable=False),
    sa.Column('hats', sa.JSON(), nullable=False),
    sa.Column('collars', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('personality', sa.String(length=64), nullable=False),
    sa.Column('clothing', sa.String(length=64), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('cleanliness', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=64), nullable=False),
    sa.Column('pet_type', sa.String(length=64), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('toy', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_clothing'), ['clothing'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_mood'), ['mood'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_personality'), ['personality'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_toy'), ['toy'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_username'))
        batch_op.drop_index(batch_op.f('ix_pet_toy'))
        batch_op.drop_index(batch_op.f('ix_pet_personality'))
        batch_op.drop_index(batch_op.f('ix_pet_mood'))
        batch_op.drop_index(batch_op.f('ix_pet_clothing'))

    op.drop_table('pet')
    op.drop_table('inventory')
    op.drop_table('graveyard')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('store')
    # ### end Alembic commands ###
